[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  PUBLIC_URL = "/"
  NODE_VERSION = "18"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true